/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package imobilizado;

import imobilizado.paineis.cadastro_conta;
import imobilizado.paineis.cadastro_usuario;
import imobilizado.paineis.icones;
import imobilizado.paineis.tabela_bem;
import imobilizado.paineis.tabela_empresa;
import imobilizado.paineis.tabela_fornecedor;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Leonardo
 */
public class Principal extends javax.swing.JFrame {
JDialog tela = null;
icones ic = null;
    /**
     * Creates new form Principa
     */
    public Principal() {
        initComponents();
        this.setExtendedState( MAXIMIZED_BOTH );
        Dimension desktopSize = this.getSize();
        desk.setBounds(this.getBounds());
        desk.setVisible(true);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new javax.swing.JDesktopPane();
        btn_clientes = new javax.swing.JButton();
        btn_empresa = new javax.swing.JButton();
        btn_conta = new javax.swing.JButton();
        btn_bem1 = new javax.swing.JButton();
        btn_bem = new javax.swing.JButton();
        btn_bem2 = new javax.swing.JButton();
        btn_bem3 = new javax.swing.JButton();
        btn_bem4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_clientes.setText("Cadastro de Usuarios");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        btn_empresa.setText("Cadastro de Empresas");
        btn_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empresaActionPerformed(evt);
            }
        });

        btn_conta.setText("Cadastro de Contas");
        btn_conta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contaActionPerformed(evt);
            }
        });

        btn_bem1.setText("Cadastro de Bens");
        btn_bem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bem1ActionPerformed(evt);
            }
        });

        btn_bem.setText("Cadastro de Fornecedores");
        btn_bem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bemActionPerformed(evt);
            }
        });

        btn_bem2.setText("Lançamentos");
        btn_bem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bem2ActionPerformed(evt);
            }
        });

        btn_bem3.setText("Consulta Depreciação");
        btn_bem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bem3ActionPerformed(evt);
            }
        });

        btn_bem4.setText("Relatórios");
        btn_bem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bem4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_bem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_bem3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_bem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_conta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_bem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_bem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1173, Short.MAX_VALUE))
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bem1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btn_bem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bem2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bem3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bem4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        desk.setLayer(btn_clientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_empresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_conta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_bem1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_bem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_bem2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_bem3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desk.setLayer(btn_bem4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Configurações");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Logout");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_contaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contaActionPerformed
        cadastro_conta cad = new cadastro_conta();
        AbreDialog(cad);

    }//GEN-LAST:event_btn_contaActionPerformed

    private void btn_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empresaActionPerformed
        tabela_empresa cad = new tabela_empresa();
        AbreDialog(cad);
        
    }//GEN-LAST:event_btn_empresaActionPerformed

    private void btn_bemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bemActionPerformed
       tabela_fornecedor cad = new tabela_fornecedor();
       AbreDialog(cad);
    }//GEN-LAST:event_btn_bemActionPerformed

    private void btn_bem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bem4ActionPerformed

    private void btn_bem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bem2ActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        cadastro_usuario cad = new cadastro_usuario();
        AbreDialog(cad);
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_bem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bem3ActionPerformed
    public void AbreDialog(JPanel p)
    {
        tela = new JDialog();
       
        //cadastro_usuario usu = new cadastro_usuario();
        
         ic = new icones();
        
        BoxLayout boxLayout = new BoxLayout(tela.getContentPane(), BoxLayout.Y_AXIS);
        ic.setSize(970, 63); 
        
        tela.getContentPane().add(p); 
        tela.getContentPane().add(ic);  

        tela.setSize(970,600);
        p.setSize(970,537);
        tela.getContentPane().setLayout(boxLayout);
        tela.setResizable(false);
        tela.setLocationRelativeTo(null);
        tela.setModal(true);
         tela.pack();
            
           
           p.setVisible(true);
           ic.setVisible(true);
        tela.setVisible(true);

    }
            
    private void btn_bem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bem1ActionPerformed
        tela = new JDialog();
       
        //cadastro_usuario usu = new cadastro_usuario();
        tabela_bem usu = new tabela_bem();
        
         ic = new icones();
        
        BoxLayout boxLayout = new BoxLayout(tela.getContentPane(), BoxLayout.Y_AXIS);
        ic.setSize(970, 63); 
        
        tela.getContentPane().add(usu); 
        tela.getContentPane().add(ic);  

        tela.setSize(970,600);
        usu.setSize(970,537);
        tela.getContentPane().setLayout(boxLayout);
        tela.setResizable(false);
        tela.setLocationRelativeTo(null);
        tela.setModal(true);
         tela.pack();
            
           
           usu.setVisible(true);
           ic.setVisible(true);
        tela.setVisible(true);

    }//GEN-LAST:event_btn_bem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_bem;
    private static javax.swing.JButton btn_bem1;
    private static javax.swing.JButton btn_bem2;
    private static javax.swing.JButton btn_bem3;
    private static javax.swing.JButton btn_bem4;
    private static javax.swing.JButton btn_clientes;
    private static javax.swing.JButton btn_conta;
    private static javax.swing.JButton btn_empresa;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
